import { DeviceClient } from './types';

/** Inert client returned while no device is selected — module-level so its
 *  identity is stable across renders. */
export const NOOP_DEVICE_CLIENT: DeviceClient = {
  platform: 'ios',
  status: 'idle',
  error: null,
  screen: null,
  fps: 0,
  devices: [],
  logs: [],
  logsEnabled: false,
  attachLogs: () => {},
  detachLogs: () => {},
  clearLogs: () => {},
  events: [],
  eventsEnabled: false,
  attachEvents: () => {},
  detachEvents: () => {},
  clearEvents: () => {},
  activity: null,
  deviceSettings: null,
  deviceSettingsPending: new Set(),
  setDeviceSetting: () => {},
  streamCapabilities: null,
  capture: null,
  streamSettings: null,
  streamSettingsPending: false,
  updateStreamSettings: () => {},
  webRtcCodec: 'h264',
  setWebRtcCodec: () => {},
  capabilities: {
    deviceSettings: false,
    activity: false,
    events: false,
    streamSettings: false,
  },
  foregroundApp: null,
  videoKind: 'img',
  attachVideo: () => {},
  sendTouch: () => {},
  sendKey: () => false,
  pressButton: () => {},
  reload: () => {},
  rotate: () => {},
  screenshot: async () => null,
  appearance: null,
  setAppearance: () => {},
  hardwareKeyboardConnected: null,
  setHardwareKeyboardConnected: () => {},
  toggleSoftwareKeyboard: () => {},
};
